[package]
name = "webvr"
version = "0.0.1"
authors = ["The Servo Project Developers"]
license = "MPL-2.0"
edition = "2018"
publish = false

[lib]
name = "webvr"
path = "lib.rs"

[features]
googlevr = ['rust-webvr/googlevr']
oculusvr = ['rust-webvr/oculusvr']
magicleap = ['rust-webvr/magicleap']
fullscreen = ['rust-webvr/fullscreen']

[dependencies]
canvas_traits = {path = "../canvas_traits"}
crossbeam-channel = "0.3"
euclid = "0.19"
ipc-channel = "0.11"
log = "0.4"
msg = {path = "../msg"}
rust-webvr-api = "0.10"
rust-webvr = {version = "0.10", features = ["openvr", "vrexternal"]}
style_traits = {path = "../style_traits"}
script_traits = {path = "../script_traits"}
servo_config = {path = "../config"}
servo_geometry = {path = "../geometry"}
webvr_traits = {path = "../webvr_traits" }
